INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Luna','2015-03-15','Golden Retriever', 30, true,'www.example.com/luna.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Max','2018-07-22','Labrador Retriever', 28, false,'www.example.com/max.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Bella','2020-12-10','Poodle', 10, true,'www.example.com/bella.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Charlie','2017-01-01','Bulldog', 25, false,'www.example.com/charlie.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Lucy','2019-05-05','Beagle', 12, true,'www.example.com/lucy.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Rocky','2016-09-09','Boxer', 27, false,'www.example.com/rocky.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Daisy','2018-02-14','Dachshund', 8, true,'www.example.com/daisy.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Buddy','2015-08-20','Shih Tzu', 6, false,'www.example.com/buddy.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Molly','2020-11-30','Yorkshire Terrier', 5, true,'www.example.com/molly.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Bailey','2019-04-25','Rottweiler', 35, false,'www.example.com/bailey.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Maggie','2017-03-02','Chihuahua', 4, true,'www.example.com/maggie.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Cooper','2020-06-18','Cocker Spaniel', 13, false,'www.example.com/cooper.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Sadie','2016-09-12','Pomeranian', 7, true,'www.example.com/sadie.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Toby','2018-07-07','Border Collie', 20, false,'www.example.com/toby.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Chloe','2020-11-11','French Bulldog', 12, true,'www.example.com/chloe.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Buster','2019-02-26','Pug', 10, false,'www.example.com/buster.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Zoey','2017-10-16','German Shepherd', 32, true,'www.example.com/zoey.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Duke','2016-04-23','Great Dane', 45, false,'www.example.com/duke.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Rosie','2019-08-29','Husky', 25, true,'www.example.com/rosie.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Oliver','2018-12-05','Maltese', 6, false,'www.example.com/oliver.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Zoe','2020-01-17','Doberman', 30, true,'www.example.com/zoe.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Jack','2015-03-13','Australian Shepherd', 23, false,'www.example.com/jack.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Lola','2017-06-21','Cavalier King Charles', 9, true,'www.example.com/lola.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Teddy','2019-10-10','Bichon Frise', 7, false,'www.example.com/teddy.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Stella','2016-05-27','Shiba Inu', 10, true,'www.example.com/stella.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Riley','2018-11-14','Chow Chow', 25, false,'www.example.com/riley.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Milo','2020-02-19','Saint Bernard', 50, true,'www.example.com/milo.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Penny','2017-07-01','Cairn Terrier', 6, false,'www.example.com/penny.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Bentley','2016-04-11','Collie', 22, true,'www.example.com/bentley.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Roxie','2019-09-30','Akita', 40, false,'www.example.com/roxie.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Winston','2018-06-08','Samoyed', 25, true,'www.example.com/winston.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Coco','2017-12-22','Miniature Schnauzer', 8, false,'www.example.com/coco.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Tucker','2020-05-05','Weimaraner', 35, true,'www.example.com/tucker.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Maddie','2016-08-18','Old English Sheepdog', 30, false,'www.example.com/maddie.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Leo','2015-09-09','Scottish Terrier', 10, true,'www.example.com/leo.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Nala','2018-03-23','Shetland Sheepdog', 12, false,'www.example.com/nala.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Gizmo','2017-07-12','Dalmatian', 25, true,'www.example.com/gizmo.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Marley','2016-10-26','Papillon', 5, false,'www.example.com/marley.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Jasper','2020-01-07','Pointer', 27, true,'www.example.com/jasper.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Pepper','2015-06-13','Greyhound', 22, false,'www.example.com/pepper.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Ginger','2018-11-03','Whippet', 15, true,'www.example.com/ginger.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Bruno','2017-04-15','Newfoundland', 60, false,'www.example.com/bruno.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Willow','2020-02-28','American Bulldog', 30, true,'www.example.com/willow.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Beau','2019-05-19','Basset Hound', 20, false,'www.example.com/beau.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Juno','2018-08-01','Pit Bull', 28, true,'www.example.com/juno.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Moose','2017-11-14','Alaskan Malamute', 35, false,'www.example.com/moose.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Millie','2020-02-07','Brittany Spaniel', 18, true,'www.example.com/millie.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Remy','2016-06-10','Vizsla', 25, false,'www.example.com/remy.jpg');
INSERT INTO mascota (nombre,fechaNac,raza,peso,tiene_chip,url_foto) VALUES('Ruby','2019-09-22','Bullmastiff', 50, true,'www.example.com/ruby.jpg');
